"""Added gender preferences to profiles

Revision ID: 839a3d19722c
Revises: 029ac8416e5b
Create Date: 2026-05-07 16:43:32.998043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839a3d19722c'
down_revision = '029ac8416e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=False, server_default='Prefer not to say'))
        batch_op.add_column(sa.Column('preferred_gender', sa.String(length=30), nullable=False, server_default='Any'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('preferred_gender')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
